Fix leak(#480)
ros2/demos pull request #481
Opened 2021-01-14 05:11 UTC by y-okumura-isp

Fix #480.
Although there are ASAN errors related to class_loader, this PR reduces one error.

Signed-off-by: y-okumura-isp <y-okumura@isp.co.jp>

2021-01-14 13:24 UTC, clalancette requested changes
One nit, and then I'm happy to approve and run CI.

2021-01-14 13:24 UTC, clalancette commented on composition/src/linktime_composition.cpp
> +  std::vector<std::shared_ptr<class_loader::ClassLoader>> loaders;
Since there is only ever going to be one owner, I would suggest using a `std::unique_ptr` here.

2021-01-18 05:13 UTC, y-okumura-isp commented
Thank you for comment.
Sorry for late reply as I studied why we should have loaders.

http://wiki.ros.org/class_loader may be the reason.

> 2.5 Understanding Loading and Unloading
> if I create an object from a class defined within a runtime library, I then unload the library, and then I try to use the object...things will go bad.

2021-01-19 13:38 UTC, clalancette approved these changes

2021-01-19 13:39 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13448)](http://ci.ros2.org/job/ci_linux/13448/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8359)](http://ci.ros2.org/job/ci_linux-aarch64/8359/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11171)](http://ci.ros2.org/job/ci_osx/11171/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=13502)](http://ci.ros2.org/job/ci_windows/13502/)

2021-01-19 15:04 UTC, clalancette commented
Windows CI is failing for a completely unrelated reason.  I think this is safe enough to put it without that, so I'm going to go ahead and merge.

2021-01-19 15:04 UTC, merged