[rolling] Update maintainers - 2022-11-08
ros2/demos pull request #589
Opened 2022-11-08 00:36 UTC by audrow

This PR updates the maintainers and code owners. The new maintainers are:
* Aditya Pande (@adityapande-1995)
* Audrow Nash (@audrow)
* Michael Jeronimo (@mjeronimo)

This PR was made with https://github.com/audrow/update-ros2-repos.

2022-11-08 13:18 UTC, clalancette requested changes

2022-11-08 13:18 UTC, clalancette commented on topic_statistics_demo/package.xml
> +  <author email="michael.jeronimo@openrobotics.org">Michael Jeronimo</author>
The xmllint problem is here.  The `<author>` tag needs to be after the `<license>` tag to meet the schema.

2022-11-08 18:58 UTC, mjeronimo approved these changes

2022-11-15 21:21 UTC, clalancette approved these changes

2022-11-15 21:34 UTC, merged