Added README.md for demo_cpp_nodes
ros2/demos pull request #599
Opened 2023-01-24 14:34 UTC by cardboardcode

## Purpose of Pull Request

This pull request adds a `README.md` to **demo_cpp_nodes** as part of efforts to address the issue highlighted in https://github.com/ros2/demos/issues/531.

2023-01-24 15:26 UTC, clalancette requested changes

2023-01-24 15:26 UTC, clalancette commented on demo_nodes_cpp/README.md
> +Compared to **Listener [Default]**, `listener_best_effort` runs a ROS2 subscribe node that sets the Quality of Service (QoS) Reliability setting to **Best Effort** via the use of **rclcpp::SensorData
```suggestion
Compared to **Listener [Default]**, `listener_best_effort` runs a ROS 2 subscriber node that sets the Quality of Service (QoS) Reliability setting to **Best Effort** via the use of **rclcpp::SensorDataQoS**, as opposed to the default **Reliable**.
Messages sent using this policy configuration attempts to deliver samples but may lose them if the network is not robust.
```

2023-01-24 15:26 UTC, clalancette commented on demo_nodes_cpp/README.md
> +This runs `content_filtering_subscriber` and `content_filtering_publisher` ROS 2 nodes which exchanges the emergency temperature data and only filters out uninteresting data so that the subscription
```suggestion
This runs `content_filtering_subscriber` and `content_filtering_publisher` ROS 2 nodes which exchanges temperature data on the `/temperature` topic.
However the subscriber requests that data is only sent if the temperature is less than -30 C or greater than 100 C, saving bandwidth.
```

2023-01-24 15:26 UTC, clalancette commented on demo_nodes_cpp/README.md
> +This runs `list_parameters` ROS 2 node which simply programmatically list example parameter names and prefixes:
```suggestion
This runs `list_parameters` ROS 2 node which simply programmatically list example parameter names and prefixes.
```

2023-01-24 15:26 UTC, clalancette commented on demo_nodes_cpp/README.md
> +This runs `set_and_get_parameters` ROS 2 node which programmatically sets and gets parameters:
```suggestion
This runs `set_and_get_parameters` ROS 2 node which programmatically sets and gets parameters.
```

2023-01-24 15:26 UTC, clalancette commented on demo_nodes_cpp/README.md
> +This runs `allocator_tutorial` ROS 2 node that publishes a `std_msgs/msg/UInt32` message that contains an integer representing the number of allocations and deallocations that happened during the pro
```suggestion
This runs `allocator_tutorial` ROS 2 node that publishes a `std_msgs/msg/UInt32` message that contains an integer representing the number of allocations and deallocations that happened during the program.
```

2023-01-24 15:26 UTC, clalancette commented on demo_nodes_cpp/README.md
> +This runs `even_parametes_node` ROS 2 node which shows a parameter callback that rejects all parameter update except tor those that set an even integer:
```suggestion
This runs `even_parametes_node` ROS 2 node which shows a parameter callback that rejects all parameter update except tor those that set an even integer.
```

2023-01-24 15:26 UTC, clalancette commented on demo_nodes_cpp/README.md
> +This runs `even_parameters_callback` ROS 2 node which triggers a callback when ROS 2 double parameter `param1` is set. The callback then sets ROS 2 double parameter `param2` to a fixed `4.0`:
```suggestion
This runs `set_parameters_callback` ROS 2 node which triggers a callback when ROS 2 double parameter `param1` is set.
The callback then sets ROS 2 double parameter `param2` to a fixed `4.0`.
```

2023-01-24 15:26 UTC, clalancette commented on demo_nodes_cpp/README.md
> +This runs `parameter_blackboard` ROS 2 node which instantiates a ROS2 parameter server which acts as "blackboard" which all nodes could get and set parametes value:
```suggestion
This runs `parameter_blackboard` ROS 2 node which instantiates a ROS 2 parameter server which acts as a global "blackboard" for all nodes to get and set parameters.
```

2023-01-25 09:29 UTC, cardboardcode commented on demo_nodes_cpp/README.md
> +Compared to **Listener [Default]**, `listener_best_effort` runs a ROS2 subscribe node that sets the Quality of Service (QoS) Reliability setting to **Best Effort** via the use of **rclcpp::SensorData
Done.

2023-01-25 09:31 UTC, cardboardcode commented on demo_nodes_cpp/README.md
> +This runs `list_parameters` ROS 2 node which simply programmatically list example parameter names and prefixes:
Done.

2023-01-25 09:31 UTC, cardboardcode commented on demo_nodes_cpp/README.md
> +This runs `set_and_get_parameters` ROS 2 node which programmatically sets and gets parameters:
Done.

2023-01-25 09:31 UTC, cardboardcode commented on demo_nodes_cpp/README.md
> +This runs `content_filtering_subscriber` and `content_filtering_publisher` ROS 2 nodes which exchanges the emergency temperature data and only filters out uninteresting data so that the subscription
Done.

2023-01-25 09:32 UTC, cardboardcode commented on demo_nodes_cpp/README.md
> +This runs `allocator_tutorial` ROS 2 node that publishes a `std_msgs/msg/UInt32` message that contains an integer representing the number of allocations and deallocations that happened during the pro
Done.

2023-01-25 09:32 UTC, cardboardcode commented on demo_nodes_cpp/README.md
> +This runs `even_parametes_node` ROS 2 node which shows a parameter callback that rejects all parameter update except tor those that set an even integer:
Done.

2023-01-25 09:33 UTC, cardboardcode commented on demo_nodes_cpp/README.md
> +This runs `even_parameters_callback` ROS 2 node which triggers a callback when ROS 2 double parameter `param1` is set. The callback then sets ROS 2 double parameter `param2` to a fixed `4.0`:
Done.

2023-01-25 09:33 UTC, cardboardcode commented on demo_nodes_cpp/README.md
> +This runs `parameter_blackboard` ROS 2 node which instantiates a ROS2 parameter server which acts as "blackboard" which all nodes could get and set parametes value:
Done.

2023-01-26 19:17 UTC, mjeronimo requested changes

2023-01-26 19:17 UTC, mjeronimo commented on demo_nodes_cpp/README.md
> +This demo provides different minimal examples of varying inter-node communcations in ROS 2.
```suggestion
This package provides several examples that demonstrate various inter-node communcations in ROS 2.
```

2023-01-26 19:17 UTC, mjeronimo commented on demo_nodes_cpp/README.md
> +This package consists of:
```suggestion
This package consists of the following examples:
```

2023-01-26 19:17 UTC, mjeronimo commented on demo_nodes_cpp/README.md
> +Similar to previous, this runs `reuse_timer` that runs a periodic timer callback that **reuses the same Wall Timer** every **3 callbacks**.
```suggestion
Similar to the previous demo, `reuse_timer` runs a periodic timer callback that **reuses the same Wall Timer** every **3 callbacks**.
```

2023-01-26 19:17 UTC, mjeronimo commented on demo_nodes_cpp/README.md
> +This runs `even_parameters_node` ROS 2 node which shows a parameter callback that rejects all parameter update except tor those that set an even integer.
```suggestion
This runs `even_parameters_node` ROS 2 node which shows a parameter callback that rejects all parameter updates except those that set an even integer.
```

2023-01-26 19:17 UTC, mjeronimo commented on demo_nodes_cpp/README.md
> +This runs a ROS 2 server that provides the service to processes two integers and outputs its sum back to ROS 2 client node.
```suggestion
This runs a ROS 2 server that provides a service to process two integers, outputting the sum back to ROS 2 client node. 
```

2023-01-27 05:16 UTC, cardboardcode commented on demo_nodes_cpp/README.md
> +This demo provides different minimal examples of varying inter-node communcations in ROS 2.
Done.

2023-01-27 05:16 UTC, cardboardcode commented on demo_nodes_cpp/README.md
> +This package consists of:
Done.

2023-01-27 05:17 UTC, cardboardcode commented on demo_nodes_cpp/README.md
> +Similar to previous, this runs `reuse_timer` that runs a periodic timer callback that **reuses the same Wall Timer** every **3 callbacks**.
Done.

2023-01-27 05:17 UTC, cardboardcode commented on demo_nodes_cpp/README.md
> +This runs `even_parameters_node` ROS 2 node which shows a parameter callback that rejects all parameter update except tor those that set an even integer.
Done.

2023-01-27 05:17 UTC, cardboardcode commented on demo_nodes_cpp/README.md
> +This runs a ROS 2 server that provides the service to processes two integers and outputs its sum back to ROS 2 client node.
Done.

2023-02-16 18:34 UTC, adityapande-1995 approved these changes

2023-02-16 18:36 UTC, merged