Added root README.md
ros2/demos pull request #601
Opened 2023-01-24 16:15 UTC by cardboardcode

## Purpose of Pull Request

This pull request adds a preface `README.md` as part of efforts to address the issue highlighted in https://github.com/ros2/demos/issues/531.

2023-01-26 22:45 UTC, mjeronimo requested changes

2023-01-26 22:45 UTC, mjeronimo commented on README.md
> +This repository contains code implementations mentioned in the official ROS 2 documentation [Tutorials](https://docs.ros.org/en/rolling/Tutorials.html).
```suggestion
This repository contains source code for demos mentioned in the official ROS 2 documentation [Tutorials](https://docs.ros.org/en/rolling/Tutorials.html).
```

2023-01-27 05:22 UTC, cardboardcode commented on README.md
> +This repository contains code implementations mentioned in the official ROS 2 documentation [Tutorials](https://docs.ros.org/en/rolling/Tutorials.html).
Done.

2023-01-31 23:56 UTC, audrow approved these changes

2023-02-16 18:37 UTC, adityapande-1995 approved these changes

2023-02-16 18:37 UTC, merged