[demo_nodes_cpp] Add YAML launch demos for topics
ros2/demos pull request #605
Opened 2023-03-08 15:30 UTC by IamPhytan

Added YAML launch file demos in `demos_nodes_cpp`.

These launch files were added in order to solve issue #[3369](https://github.com/ros2/ros2_documentation/issues/3369) in [`ros2_documentation`](https://github.com/ros2/ros2_documentation).

2023-03-08 21:04 UTC, clalancette requested changes
Can you please rename these files to use `_launch.yaml` at the end instead?  We are trying to move away from the `.launch.yaml`; see also https://github.com/ros2/demos/pull/588

2023-03-09 01:56 UTC, IamPhytan commented
The files have been renamed. I may also rename current launch files to comply with this new standard

2023-03-09 19:00 UTC, clalancette approved these changes

2023-03-09 19:00 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18201)](http://ci.ros2.org/job/ci_linux/18201/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12733)](http://ci.ros2.org/job/ci_linux-aarch64/12733/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18861)](http://ci.ros2.org/job/ci_windows/18861/)

2023-03-09 19:29 UTC, fujitatomoya approved these changes

2023-03-09 22:11 UTC, merged